/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DigicrystalRouteImport } from './routes/digicrystal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WebsiteSecurityAssessmentRouteImport } from './routes/website-security-assessment'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminProjectRequestsRouteImport } from './routes/admin/project-requests'
import { Route as DemoCenterIndexRouteImport } from './routes/demo-center.index'
import { Route as DemoCenterSecurityReportRouteImport } from './routes/demo-center.security-report'
import { Route as DemoCenterTestingDashboardRouteImport } from './routes/demo-center.testing-dashboard'
import { Route as DemoCenterVulnerabilityDashboardRouteImport } from './routes/demo-center.vulnerability-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DigicrystalRoute = DigicrystalRouteImport.update({
  id: '/digicrystal',
  path: '/digicrystal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteSecurityAssessmentRoute =
  WebsiteSecurityAssessmentRouteImport.update({
    id: '/website-security-assessment',
    path: '/website-security-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectRequestsRoute = AdminProjectRequestsRouteImport.update({
  id: '/admin/project-requests',
  path: '/admin/project-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCenterIndexRoute = DemoCenterIndexRouteImport.update({
  id: '/demo-center/',
  path: '/demo-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCenterSecurityReportRoute =
  DemoCenterSecurityReportRouteImport.update({
    id: '/demo-center/security-report',
    path: '/demo-center/security-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoCenterTestingDashboardRoute =
  DemoCenterTestingDashboardRouteImport.update({
    id: '/demo-center/testing-dashboard',
    path: '/demo-center/testing-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoCenterVulnerabilityDashboardRoute =
  DemoCenterVulnerabilityDashboardRouteImport.update({
    id: '/demo-center/vulnerability-dashboard',
    path: '/demo-center/vulnerability-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digicrystal': typeof DigicrystalRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/website-security-assessment': typeof WebsiteSecurityAssessmentRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/project-requests': typeof AdminProjectRequestsRoute
  '/demo-center/security-report': typeof DemoCenterSecurityReportRoute
  '/demo-center/testing-dashboard': typeof DemoCenterTestingDashboardRoute
  '/demo-center/vulnerability-dashboard': typeof DemoCenterVulnerabilityDashboardRoute
  '/demo-center/': typeof DemoCenterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digicrystal': typeof DigicrystalRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/website-security-assessment': typeof WebsiteSecurityAssessmentRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/project-requests': typeof AdminProjectRequestsRoute
  '/demo-center/security-report': typeof DemoCenterSecurityReportRoute
  '/demo-center/testing-dashboard': typeof DemoCenterTestingDashboardRoute
  '/demo-center/vulnerability-dashboard': typeof DemoCenterVulnerabilityDashboardRoute
  '/demo-center': typeof DemoCenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digicrystal': typeof DigicrystalRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/website-security-assessment': typeof WebsiteSecurityAssessmentRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/project-requests': typeof AdminProjectRequestsRoute
  '/demo-center/security-report': typeof DemoCenterSecurityReportRoute
  '/demo-center/testing-dashboard': typeof DemoCenterTestingDashboardRoute
  '/demo-center/vulnerability-dashboard': typeof DemoCenterVulnerabilityDashboardRoute
  '/demo-center/': typeof DemoCenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/digicrystal'
    | '/how-it-works'
    | '/privacy'
    | '/services'
    | '/start-project'
    | '/terms'
    | '/website-security-assessment'
    | '/admin/content'
    | '/admin/project-requests'
    | '/demo-center/security-report'
    | '/demo-center/testing-dashboard'
    | '/demo-center/vulnerability-dashboard'
    | '/demo-center/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/digicrystal'
    | '/how-it-works'
    | '/privacy'
    | '/services'
    | '/start-project'
    | '/terms'
    | '/website-security-assessment'
    | '/admin/content'
    | '/admin/project-requests'
    | '/demo-center/security-report'
    | '/demo-center/testing-dashboard'
    | '/demo-center/vulnerability-dashboard'
    | '/demo-center'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/digicrystal'
    | '/how-it-works'
    | '/privacy'
    | '/services'
    | '/start-project'
    | '/terms'
    | '/website-security-assessment'
    | '/admin/content'
    | '/admin/project-requests'
    | '/demo-center/security-report'
    | '/demo-center/testing-dashboard'
    | '/demo-center/vulnerability-dashboard'
    | '/demo-center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DigicrystalRoute: typeof DigicrystalRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  StartProjectRoute: typeof StartProjectRoute
  TermsRoute: typeof TermsRoute
  WebsiteSecurityAssessmentRoute: typeof WebsiteSecurityAssessmentRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminProjectRequestsRoute: typeof AdminProjectRequestsRoute
  DemoCenterSecurityReportRoute: typeof DemoCenterSecurityReportRoute
  DemoCenterTestingDashboardRoute: typeof DemoCenterTestingDashboardRoute
  DemoCenterVulnerabilityDashboardRoute: typeof DemoCenterVulnerabilityDashboardRoute
  DemoCenterIndexRoute: typeof DemoCenterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digicrystal': {
      id: '/digicrystal'
      path: '/digicrystal'
      fullPath: '/digicrystal'
      preLoaderRoute: typeof DigicrystalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-security-assessment': {
      id: '/website-security-assessment'
      path: '/website-security-assessment'
      fullPath: '/website-security-assessment'
      preLoaderRoute: typeof WebsiteSecurityAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/project-requests': {
      id: '/admin/project-requests'
      path: '/admin/project-requests'
      fullPath: '/admin/project-requests'
      preLoaderRoute: typeof AdminProjectRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-center/': {
      id: '/demo-center/'
      path: '/demo-center'
      fullPath: '/demo-center/'
      preLoaderRoute: typeof DemoCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-center/security-report': {
      id: '/demo-center/security-report'
      path: '/demo-center/security-report'
      fullPath: '/demo-center/security-report'
      preLoaderRoute: typeof DemoCenterSecurityReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-center/testing-dashboard': {
      id: '/demo-center/testing-dashboard'
      path: '/demo-center/testing-dashboard'
      fullPath: '/demo-center/testing-dashboard'
      preLoaderRoute: typeof DemoCenterTestingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-center/vulnerability-dashboard': {
      id: '/demo-center/vulnerability-dashboard'
      path: '/demo-center/vulnerability-dashboard'
      fullPath: '/demo-center/vulnerability-dashboard'
      preLoaderRoute: typeof DemoCenterVulnerabilityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DigicrystalRoute: DigicrystalRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  StartProjectRoute: StartProjectRoute,
  TermsRoute: TermsRoute,
  WebsiteSecurityAssessmentRoute: WebsiteSecurityAssessmentRoute,
  AdminContentRoute: AdminContentRoute,
  AdminProjectRequestsRoute: AdminProjectRequestsRoute,
  DemoCenterSecurityReportRoute: DemoCenterSecurityReportRoute,
  DemoCenterTestingDashboardRoute: DemoCenterTestingDashboardRoute,
  DemoCenterVulnerabilityDashboardRoute: DemoCenterVulnerabilityDashboardRoute,
  DemoCenterIndexRoute: DemoCenterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
